---
apiVersion: deviceregistry.microsoft.com/v1
kind: AssetEndpointProfile
metadata:
  name: {{ .Values.asset.name | default "device-001" }} # Needs to match the asset name
  namespace: {{ .Values.namespace | default "azure-iot-operations" }}
spec:
  authentication:
    method: UsernamePassword
    usernamePasswordCredentials:
      usernameSecretName: aio-dds-connector-aep-creds/username
      passwordSecretName: aio-dds-connector-aep-creds/password
  endpointProfileType: {{ .Values.assetEndpointProfile.type }}
  targetAddress: {{ .Values.assetEndpointProfile.targetAddress }}
  # Is the UUID required?
  #uuid: 3d83f8be-9874-4f82-8538-84b7fced7f74
