# There is no support at this time for upgrading or deleting CRDs using Helm.
# https://helm.sh/docs/chart_best_practices/custom_resource_definitions/
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.15.0
  creationTimestamp: "2025-06-05T12:59:04Z"
  generation: 1
  name: assets.deviceregistry.microsoft.com
  resourceVersion: "5562"
  uid: 5a3c8c5f-8caa-4a4b-917e-530181855b37
spec:
  conversion:
    strategy: None
  group: deviceregistry.microsoft.com
  names:
    kind: Asset
    listKind: AssetList
    plural: assets
    singular: asset
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Asset is the Schema for the assets API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: AssetSpec defines the desired state of Asset
            properties:
              assetEndpointProfileRef:
                description: A reference to the asset endpoint profile (connection
                  information) used by brokers to connect to an endpoint that provides
                  data points for this asset. Must have the format <ModuleCR.metadata.namespace>/<ModuleCR.metadata.name>.
                type: string
              attributes:
                description: A set of key-value pairs that contain custom attributes
                  set by the customer.
                type: object
                x-kubernetes-preserve-unknown-fields: true
              datasets:
                description: Array of data sets that are part of the asset. Each data
                  set describes the data points that make up the set.
                items:
                  properties:
                    dataPoints:
                      description: Array of data points that are part of the dataset.
                        Each data point can have per-data point configuration.
                      items:
                        properties:
                          dataPointConfiguration:
                            description: Stringified JSON that contains connector-specific
                              configuration for the data point. For OPC UA, this could
                              include configuration like, publishingInterval, samplingInterval,
                              and queueSize.
                            type: string
                          dataSource:
                            description: The address of the source of the data in
                              the asset (e.g. URL) so that a client can access the
                              data source on the asset.
                            type: string
                          name:
                            description: The name of the data point.
                            type: string
                          observabilityMode:
                            default: None
                            description: An indication of how the data point should
                              be mapped to OpenTelemetry.
                            enum:
                            - None
                            - Counter
                            - Gauge
                            - Histogram
                            - Log
                            type: string
                        required:
                        - dataSource
                        - name
                        type: object
                      maxItems: 1000
                      type: array
                    datasetConfiguration:
                      description: Stringified JSON that contains connector-specific
                        JSON string that describes configuration for the specific
                        dataset.
                      type: string
                    name:
                      description: Name of the dataset.
                      type: string
                    topic:
                      description: Object that describes the topic information for
                        the specific dataset.
                      properties:
                        path:
                          description: The topic path for messages published to an
                            MQTT broker.
                          type: string
                        retain:
                          default: Never
                          description: 'When set to ''Keep'', messages published to
                            an MQTT broker will have the retain flag set. Default:
                            ''Never''.'
                          enum:
                          - Keep
                          - Never
                          type: string
                      required:
                      - path
                      type: object
                  required:
                  - name
                  type: object
                maxItems: 1000
                type: array
              defaultDatasetsConfiguration:
                description: Stringified JSON that contains connector-specific default
                  configuration for all datasets. Each dataset can have its own configuration
                  that overrides the default settings here.
                type: string
              defaultEventsConfiguration:
                description: Stringified JSON that contains connector-specific default
                  configuration for all events. Each event can have its own configuration
                  that overrides the default settings here.
                type: string
              defaultTopic:
                description: Object that describes the default topic information for
                  the asset.
                properties:
                  path:
                    description: The topic path for messages published to an MQTT
                      broker.
                    type: string
                  retain:
                    default: Never
                    description: 'When set to ''Keep'', messages published to an MQTT
                      broker will have the retain flag set. Default: ''Never''.'
                    enum:
                    - Keep
                    - Never
                    type: string
                required:
                - path
                type: object
              description:
                description: Human-readable description of the asset.
                type: string
              discoveredAssetRefs:
                description: Reference to a list of discovered assets. Populated only
                  if the asset has been created from discovery flow. Discovered asset
                  names must be provided.
                items:
                  type: string
                type: array
              displayName:
                description: Human-readable display name.
                type: string
              documentationUri:
                description: Reference to the documentation.
                type: string
              enabled:
                description: Enabled/Disabled status of the asset.
                type: boolean
              events:
                description: Array of events that are part of the asset. Each event
                  can have per-event configuration.
                items:
                  properties:
                    eventConfiguration:
                      description: Stringified JSON that contains connector-specific
                        configuration for the event. For OPC UA, this could include
                        configuration like, publishingInterval, samplingInterval,
                        and queueSize.
                      type: string
                    eventNotifier:
                      description: The address of the notifier of the event in the
                        asset (e.g. URL) so that a client can access the event on
                        the asset.
                      type: string
                    name:
                      description: The name of the event.
                      type: string
                    observabilityMode:
                      default: None
                      description: An indication of how the event should be mapped
                        to OpenTelemetry.
                      enum:
                      - None
                      - Log
                      type: string
                    topic:
                      description: Object that describes the topic information for
                        the specific event.
                      properties:
                        path:
                          description: The topic path for messages published to an
                            MQTT broker.
                          type: string
                        retain:
                          default: Never
                          description: 'When set to ''Keep'', messages published to
                            an MQTT broker will have the retain flag set. Default:
                            ''Never''.'
                          enum:
                          - Keep
                          - Never
                          type: string
                      required:
                      - path
                      type: object
                  required:
                  - eventNotifier
                  - name
                  type: object
                maxItems: 1000
                type: array
              externalAssetId:
                description: Asset id provided by the customer.
                type: string
              hardwareRevision:
                description: Revision number of the hardware.
                type: string
              manufacturer:
                description: Asset manufacturer name.
                type: string
              manufacturerUri:
                description: Asset manufacturer URI.
                type: string
              model:
                description: Asset model name.
                type: string
              productCode:
                description: Asset product code.
                type: string
              serialNumber:
                description: Asset serial number.
                type: string
              softwareRevision:
                description: Revision number of the software.
                type: string
              uuid:
                description: Globally unique, immutable, non-reusable id.
                type: string
              version:
                description: An integer that is incremented each time the resource
                  is modified.
                format: int64
                type: integer
            required:
            - assetEndpointProfileRef
            type: object
          status:
            description: AssetStatus defines the observed state of Asset
            properties:
              datasets:
                description: Array of dataset statuses that describe the status of
                  each dataset.
                items:
                  properties:
                    messageSchemaReference:
                      description: The message schema reference object.
                      properties:
                        schemaName:
                          description: The reference to the message schema name.
                          type: string
                        schemaRegistryNamespace:
                          description: The reference to the message schema registry
                            namespace.
                          type: string
                        schemaVersion:
                          description: The reference to the message schema version.
                          type: string
                      required:
                      - schemaName
                      - schemaRegistryNamespace
                      - schemaVersion
                      type: object
                    name:
                      description: The name of the dataset. Must be unique within
                        the status.datasets array. This name is used to correlate
                        between the spec and status dataset information.
                      type: string
                  required:
                  - name
                  type: object
                type: array
              errors:
                description: Array object to transfer and persist errors that originate
                  from the Edge.
                items:
                  properties:
                    code:
                      description: 'Error code for classification of errors (ex: 400,
                        404, 500, etc.).'
                      format: int32
                      type: integer
                    message:
                      description: 'Human readable helpful error message to provide
                        additional context for error (ex: “capability Id ''foo'' does
                        not exist”).'
                      type: string
                  type: object
                type: array
              events:
                description: Array of event statuses that describe the status of each
                  event.
                items:
                  properties:
                    messageSchemaReference:
                      description: The message schema reference object.
                      properties:
                        schemaName:
                          description: The reference to the message schema name.
                          type: string
                        schemaRegistryNamespace:
                          description: The reference to the message schema registry
                            namespace.
                          type: string
                        schemaVersion:
                          description: The reference to the message schema version.
                          type: string
                      required:
                      - schemaName
                      - schemaRegistryNamespace
                      - schemaVersion
                      type: object
                    name:
                      description: The name of the event. Must be unique within the
                        status.events array. This name is used to correlate between
                        the spec and status event information.
                      type: string
                  required:
                  - name
                  type: object
                type: array
              version:
                description: A read only incremental counter indicating the number
                  of times the configuration has been modified from the perspective
                  of the current actual (Edge) state of the Asset. Edge would be the
                  only writer of this value and would sync back up to the cloud. In
                  steady state, this should equal version.
                format: int64
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: Asset
    listKind: AssetList
    plural: assets
    singular: asset
  conditions:
  - lastTransitionTime: "2025-06-05T12:59:04Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2025-06-05T12:59:04Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
